// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/3/2026, 10:38:52 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/marco/Claude/wellbeintouch-project/wellbeintouch/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/plugins/**/*.{js,ts,mjs}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/composables/**/*.{js,ts,mjs}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/utils/**/*.{js,ts,mjs}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marco/Claude/wellbeintouch-project/wellbeintouch/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;